services:

  # Postgres
  db:
    hostname: pg
    image: postgres:16.3-alpine3.20
    env_file:
      - ./.env
    networks:
      - db-net
    volumes:
      - db:/var/lib/postgresql/data/db-files/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U flask_app" ]
      interval: 5s
      timeout: 5s
      retries: 5

  # App  
  app:
    hostname: app
    #image_app:
    build:
      context: .
      dockerfile: Dockerfile.app
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-net
      - db-net
    restart: always
      
  # Nginx  
  nginx:
    hostname: nginx
    container_name: nginx
    #image_nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - app-net
    restart: always

volumes:
  db:
  mydata:
    external: true 

networks:
  app-net:
  db-net:
