name: Exptracker

on:
  workflow_dispatch:
    inputs:
      image:
        description: "Choose environment"
        type: choice
        options:
          - exptracker-dev
          - exptracker-prod
        required: true
        default: exptracker-dev       
      version:
        description: "Choose Version"
        type: string
        required: false
        default: 0.0.1
      test_only:
        description: "Skip Deploy"
        type: boolean
        required: false
        default: false

run-name: "${{ github.workflow }} - ${{ inputs.image }}:${{ inputs.version }}"

env:
  ECR_URI: "644435390668.dkr.ecr.ap-south-1.amazonaws.com/"
  APP_DOCKERFILE: "Dockerfile.app"
  NGINX_DOCKERFILE: "Dockerfile.nginx"
  APP_NAME: "app-${{ inputs.image }}"
  NGINX_NAME: "nginx-${{ inputs.image }}"
  BUILD_NUMBER: "${{ github.run_number }}"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: build app
        run: docker build -f ${{ env.APP_DOCKERFILE }} -t ${{ env.APP_NAME }}:${{ env.BUILD_NUMBER }} .

      - name: build nginx
        run: docker build -f ${{ env.NGINX_DOCKERFILE }} -t ${{ env.NGINX_NAME }}:${{ env.BUILD_NUMBER }} .

      - name: E2E tests
        run: |
          mv env.example .env
          sed -i 's/#image_app:.*$/image: ${{ env.APP_NAME }}:${{ env.BUILD_NUMBER }}/' docker-compose.yml
          sed -i 's/#image_nginx:.*$/image: ${{ env.NGINX_NAME }}:${{ env.BUILD_NUMBER }}/' docker-compose.yml
          docker compose up -d
          chmod +x ./tests/healthcheck.sh
          chmod +x ./tests/e2e.sh
          ./tests/healthcheck.sh nginx 30 5
          ./tests/e2e.sh
        env:
          FLASK_SECRET_KEY: "test_value"
          JWT_SECRET_KEY: "test_value"
          PG_HOST: "test_value"
          PG_PORT: 5432   
          POSTGRES_PASSWORD: "test_value"
          POSTGRES_USER: "test_value"
          POSTGRES_DB: "test_value"
          PGDATA: "/var/lib/postgresql/data/db-files/"


           
  
      

        
      
