name: Exptracker

on:
  workflow_dispatch:
    inputs:
      image:
        description: "Choose environment"
        type: choice
        options:
          - dev
          - prod
        required: true
        default: dev    
      version:
        description: "Choose Version"
        type: string
        required: false
        default: 0.0.1
      test_only:
        description: "Skip Deploy"
        type: boolean
        required: false
        default: false

run-name: "${{ github.workflow }}-${{ inputs.image }}:${{ inputs.version }}"

env:
  ECR_URI: "644435390668.dkr.ecr.ap-south-1.amazonaws.com/dan-exptracker"
  AWS_REGION: "ap-south-1"
  APP_DOCKERFILE: "Dockerfile.app"
  NGINX_DOCKERFILE: "Dockerfile.nginx"
  APP_NAME: "app-${{ inputs.image }}"
  NGINX_NAME: "nginx-${{ inputs.image }}"
  BUILD_NUMBER: "${{ github.run_number }}"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker Images
        run: |
          docker build -f ${{ env.APP_DOCKERFILE }} -t ${{ env.APP_NAME }}:${{ env.BUILD_NUMBER }} .
          docker build -f ${{ env.NGINX_DOCKERFILE }} -t ${{ env.NGINX_NAME }}:${{ env.BUILD_NUMBER }} .

      - name: Setup Testing Environment
        run: |
          mv env.example .env
          sed -i 's/#image_app:.*$/image: ${{ env.APP_NAME }}:${{ env.BUILD_NUMBER }}/' docker-compose.yml
          sed -i 's/#image_nginx:.*$/image: ${{ env.NGINX_NAME }}:${{ env.BUILD_NUMBER }}/' docker-compose.yml
          docker compose up -d
          chmod +x ./tests/healthcheck.sh
          chmod +x ./tests/e2e.sh

      - name: Run E2E Tests
        run: |
          ./tests/healthcheck.sh localhost 30 5
          ./tests/e2e.sh localhost

      - name: Determine Version
        if: ${{ !inputs.test_only }}
        run: |
          commit_msg=$(git log -1 --pretty=%B | tr -d '\n')
          echo "Commit Message: $commit_msg"
          
          last_tag=$(git tag --list '[0-9]*.[0-9]*.[0-9]*' | sort -V | tail -n 1)
          echo "Last tag: $last_tag"
          
          if [ -z "$last_tag" ]; then
            new_version="1.0.0"
          else
            major=$(echo "$last_tag" | cut -d. -f1)
            minor=$(echo "$last_tag" | cut -d. -f2)
            patch=$(( $(echo "$last_tag" | cut -d. -f3) + 1 ))
            new_version="$major.$minor.$patch"
          fi
          echo "New version: $new_version"
        shell: bash

      - name: Configure AWS Credentials
        if: ${{ !inputs.test_only }}
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Authenticate Docker ECR
        if: ${{ !inputs.test_only }}
        run: aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.ECR_URI }}

      - name: Tag and Push Image to ECR
        if: ${{ !inputs.test_only }}
        run: |
          docker tag ${{ env.APP_NAME }}:${{ env.BUILD_NUMBER }} ${{ env.ECR_URI }}:${{ inputs.version }}
          docker push ${{ env.ECR_URI }}:${{ inputs.version }}
